# Schema for IBEW Theme settings
ibew_theme.settings:
  type: theme_settings
  label: 'Local 11 Settings'
  mapping:
    canvas:
      type: mapping
      label: 'Drupal Canvas Settings'
      mapping:
        use_canvas:
          type: boolean
          label: 'Use Drupal Canvas'
        editable:
          type: sequence
          label: 'Editable Regions'
          sequence:
            type: boolean
            label: 'Region Status'
    top_bar_show:
      type: boolean
      label: 'Show Top Bar'
    top_bar_address:
      type: string
      label: 'Address Text'
    top_bar_phone:
      type: string
      label: 'Phone Number'
    top_bar_email:
      type: string
      label: 'Email Address'
    top_bar_join_link:
      type: string
      label: 'Join URL'
    top_bar_join_text:
      type: string
      label: 'Join Link Text'
    social_facebook:
      type: string
      label: 'Facebook URL'
    social_twitter:
      type: string
      label: 'Twitter / X URL'
    social_linkedin:
      type: string
      label: 'LinkedIn URL'
    social_instagram:
      type: string
      label: 'Instagram URL'
    
    # Light Mode Colors
    ibew_light_primary:
      type: string
      label: 'Light Mode Primary Color'
    ibew_light_secondary:
      type: string
      label: 'Light Mode Secondary Color'
    ibew_light_accent:
      type: string
      label: 'Light Mode Accent Color'
    ibew_light_bg:
      type: string
      label: 'Light Mode Background Color'
    ibew_light_card_bg:
      type: string
      label: 'Light Mode Card Background Color'
    ibew_light_text:
      type: string
      label: 'Light Mode Text Color'

    # Dark Mode Colors
    ibew_dark_primary:
      type: string
      label: 'Dark Mode Primary Color'
    ibew_dark_secondary:
      type: string
      label: 'Dark Mode Secondary Color'
    ibew_dark_accent:
      type: string
      label: 'Dark Mode Accent Color'
    ibew_dark_bg:
      type: string
      label: 'Dark Mode Background Color'
    ibew_dark_card_bg:
      type: string
      label: 'Dark Mode Card Background Color'
    ibew_dark_text:
      type: string
      label: 'Dark Mode Text Color'
